[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"

[context.branch-deploy.environment]
  NODE_ENV = "development"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true